#!/bin/bash/
fun()
{
cat header >  $1t
cat $2/$1  >> $1t
cat footer >> $1t
}

fun ADAL.c  /home/ubuntu/git/repo.1
fun BASC.c  /home/ubuntu/git/repo.1
fun BRAC.c  /home/ubuntu/git/repo.1
fun DCOD.c  /home/ubuntu/git/repo.1
fun GTUR.c  /home/ubuntu/git/repo.1
fun INSP.c  /home/ubuntu/git/repo.1
fun IO.c    /home/ubuntu/git/repo.1
fun IOCTL.c /home/ubuntu/git/repo.1
